# Stamp a Unix timestamp from an always-out-of-date target. Configure-time
# generation would leave the id unchanged across ordinary rebuilds.

if(NOT DEFINED TOMAHAWK56_BUILD_ID_HEADER)
  message(FATAL_ERROR "TOMAHAWK56_BUILD_ID_HEADER must be set")
endif()

string(TIMESTAMP TOMAHAWK56_BUILD_ID "%s" UTC)

file(WRITE "${TOMAHAWK56_BUILD_ID_HEADER}"
"/* Generated by config/cmake/tomahawk56_build_id.cmake - do not edit. */
#pragma once

#define TOMAHAWK56_BUILD_ID ${TOMAHAWK56_BUILD_ID}U
")
