manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tomahawk-keyboards
      url-base: https://github.com/Tomahawk-Keyboards
  projects:
    - name: zmk
      remote: tomahawk-keyboards
      revision: modify_backlight_layer
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: tomahawk-keyboards
      revision: main
  self:
    path: config
